# List
api_url_list~json:
    path:       /url/list
    defaults:   { _controller: ApiBundle:Url:list }
    methods:    [GET]

# Simple CRUD Actions
api_url_create~json:
    path:       /url/create
    defaults:   { _controller: ApiBundle:Url:create }
    methods:    [POST]

api_url_update~json:
    path:       /url/update
    defaults:   { _controller: ApiBundle:Url:update }
    methods:    [PUT]