# API List
api_url_list~json:
    path:       /api/url/list
    defaults:   { _controller: ApiBundle:Url:list }
    methods:    [GET]

# API Redirect
api_url_redirect~json:
    path:       /api/url/redirect
    defaults:   { _controller: ApiBundle:Url:redirect }
    methods:    [GET]

# API Simple CRUD Actions
api_url_create~json:
    path:       /api/url/create
    defaults:   { _controller: ApiBundle:Url:create }
    methods:    [POST]

api_url_update~json:
    path:       /api/url/update
    defaults:   { _controller: ApiBundle:Url:update }
    methods:    [PUT]

#Browser actions
redirect:
    path:       /{tinyUrl}
    defaults:   { _controller: ApiBundle:Default:redirect }
    methods:    [GET]

index:
    path:       /
    defaults:   { _controller: ApiBundle:Default:index }
    methods:    [GET]
